### ISSUE TITLE
basic_usage IPython notebook kills the kernel

### ISSUE THREAD

**Issue by petebachant** [idies/pyJHTDB#11]
Using the newest stable versions of Python 3.4, IPython from the Conda repositories, attempting to run all cells in `basic_usage.ipynb` kills the kernel. Top level `tests.py` script seems to run fine, though there is no output.

**Comment by chichilalescu** [comment]
I can't reproduce this. Here's what I have:

@chichi-G:~/repos/pyJHTDB/examples$ ipython --version
2.3.1
@chichi-G:~/repos/pyJHTDB/examples$ python --version
Python 3.4.0
@chichi-G:~/repos/pyJHTDB/examples$ ipython notebook --version
2.3.1

What's the ipython version you're using?

Best,
Chichi L


On 03/18/2015 12:53 PM, Pete Bachant wrote:
> Using the newest stable versions of Python 3.4, IPython from the Conda
> repositories, attempting to run all cells in |basic_usage.ipynb| kills
> the kernel. Top level |tests.py| script seems to run fine, though there
> is no output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idies/pyJHTDB/issues/11>.
>

-- 
Cristian Constantin Lalescu
Postdoctoral Researcher
Department of Applied Mathematics & Statistics
3400 North Charles Street
The Johns Hopkins University
Baltimore, Maryland 21218-2682 USA

**Comment by petebachant** [comment]
I am running IPython 3.0.0.

**Comment by chichilalescu** [comment]
I just upgraded ipython through pip, it's now at 3.0.0. basic_usage.ipynb still works fine though.
Could you show me the full output from the server?
I'm not sure how you're loading the notebook now, but please open it from a console, with "ipython notebook basic_usage.ipynb". That's gonna show a whole bunch of output, hopefully there's some error message in there.

**Comment by petebachant** [comment]
That is how I was launching it before. Here's my output after trying to run all cells:

```bash
$ ipython notebook basic_usage.ipynb
[I 13:14:59.074 NotebookApp] Using existing profile dir: '/home/pete/.ipython/profile_default'
[I 13:14:59.077 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 13:14:59.092 NotebookApp] Serving notebooks from local directory: /home/pete/Downloads/pyJHTDB/examples
[I 13:14:59.092 NotebookApp] 0 active kernels 
[I 13:14:59.092 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 13:14:59.092 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[W 13:15:00.012 NotebookApp] Notebook basic_usage.ipynb is not trusted
[I 13:15:00.185 NotebookApp] Kernel started: 830fd4eb-cf39-48c3-a457-aa1228e2d5fe
0: SOAP 1.2 fault: SOAP-ENV:Receiver [no subcode]
"System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.Exception: Request size too large (16384 > 4096)
   at TurbulenceService.AuthInfo.VerifyToken(String tokenString, Int32 reqsize) in C:\Users\kalin\Documents\Turbulence-git\Turbulence\TurbulenceWebServiceLibrary\AuthInfo.cs:line 54
   at TurbulenceService.TurbulenceService.GetVelocity(String authToken, String dataset, Single time, SpatialInterpolation spatialInterpolation, TemporalInterpolation temporalInterpolation, Point3[] points) in c:\www\turbulence.pha.jhu.edu\App_Code\WebService.cs:line 74
   --- End of inner exception stack trace ---"
Detail: [no detail]

[I 13:15:24.186 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 830fd4eb-cf39-48c3-a457-aa1228e2d5fe restarted
```

Something is apparently going wrong with the auth token?

**Comment by chichilalescu** [comment]
Yes, you're apparently using the default authorization token.
If you already have your own authorization token, please place it in 
.config/JHTDB in your home folder. This folder should have already been 
created.

The "Request size too large (16384 > 4096)" is the error I needed to see.

Apparently, I do have to have a smaller request by default in this 
notebook, so the picture is going to be ugly...

Best,
Chichi L

On 03/18/2015 01:17 PM, Pete Bachant wrote:
> That is how I was launching it before. Here's my output after trying to
> run all cells:
>
> $ ipython notebook basic_usage.ipynb
> [I 13:14:59.074 NotebookApp] Using existing profile dir:'/home/pete/.ipython/profile_default'
> [I 13:14:59.077 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
> [I 13:14:59.092 NotebookApp] Serving notebooks fromlocal  directory: /home/pete/Downloads/pyJHTDB/examples
> [I 13:14:59.092 NotebookApp] 0 active kernels
> [I 13:14:59.092 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
> [I 13:14:59.092 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> Created new windowin  existing browser session.
> [W 13:15:00.012 NotebookApp] Notebook basic_usage.ipynb is not trusted
> [I 13:15:00.185 NotebookApp] Kernel started: 830fd4eb-cf39-48c3-a457-aa1228e2d5fe
> 0: SOAP 1.2 fault: SOAP-ENV:Receiver [no subcode]
> "System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.Exception: Request size too large (16384 > 4096)
>     at TurbulenceService.AuthInfo.VerifyToken(String tokenString, Int32 reqsize) in C:\Users\kalin\Documents\Turbulence-git\Turbulence\TurbulenceWebServiceLibrary\AuthInfo.cs:line 54
>     at TurbulenceService.TurbulenceService.GetVelocity(String authToken, String dataset, Single time, SpatialInterpolation spatialInterpolation, TemporalInterpolation temporalInterpolation, Point3[] points) in c:\www\turbulence.pha.jhu.edu\App_Code\WebService.cs:line 74
>     --- End of inner exception stack trace ---"
> Detail: [no detail]
>
> [I 13:15:24.186 NotebookApp] KernelRestarter: restarting kernel (1/5)
> WARNING:root:kernel 830fd4eb-cf39-48c3-a457-aa1228e2d5fe restarted
>
> Something is apparently going wrong with the auth token?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idies/pyJHTDB/issues/11#issuecomment-83064823>.
>

-- 
Cristian Constantin Lalescu
Postdoctoral Researcher
Department of Applied Mathematics & Statistics
3400 North Charles Street
The Johns Hopkins University
Baltimore, Maryland 21218-2682 USA

**Comment by petebachant** [comment]
Going to close this since it works with a proper auth token.
