### ISSUE TITLE
Time info for channel flow is too short

### ISSUE THREAD

**Issue by GrigorySarnitsky** [idies/pyJHTDB#16]
Right now pyJHTDB.dbinfo.channel['time'][-1] equals to 6.6495004 and 'time' has only 1024 points whereas it should be 4 times more, up to 25.9935

I can use getData to get data for times up to 25.9935

**Comment by chichilalescu** [comment]
@sshamilton , I'm a little out of date.
Could you please go through the data and tell me  how many timesteps there are in the channel and isotropic datasets?
I guess the timestep is the same as before, and I just need to update the dbinfo.py file.

**Comment by sshamilton** [comment]
@chichilalescu Channel has always had 25.9935 as @GrigorySarnitsky mentioned, and we extended isotropic1024coarse to 10.056 last October, so we should update the code.

**Comment by sshamilton** [comment]
Ok, I've updated it.
