### ISSUE TITLE
Installation with Anaconda

### ISSUE THREAD

**Issue by alexlib** [idies/pyJHTDB#19]
I installed pyJHTDB on Ubuntu 16.04 with Anaconda Python 3.6 (it includes h5py, numpy, sympy and scipy by default). If it's of interest for anyone, the steps are: 

1. Download Anaconda https://www.anaconda.com/download/#linux
2. Install using `bash Anaconda-latest-Linux-x86_64.sh`
3. Install pyJHTDB using `pip` and HDF5 library that is included in Anaconda (a part of h5py): 
` pip install pyJHTDB --global-option=build_ext --global-option="-I/home/alex/anaconda3/include" `
note the path to the `anaconda3` directory, replace it with your path.

**Comment by erichson** [comment]
@alexlib thanks for sharing. This did the trick for me!

**Comment by erichson** [comment]
Well, it turned out that the pip version is pretty old and misses some import functions like ```lTDB.add_token(auth_token)```. Anyway, ```python setup.py install``` worked in combination with anaconda after setting ```HDF5_ON = False```. There is certainly a better way... but this hack does the trick for me.

Best,
Ben

**Comment by rohitravoori** [comment]
The pip package has been updated and can be installed with a simple **pip install pyJHTDB** now.

**Comment by rohitravoori** [comment]
The pip package has been updated and can be installed with a simple pip install pyJHTDB now.

**Comment by petebachant** [comment]
What do we need to do to the repo to allow `pip install .` to find HDF5 without the additional arguments running `setup.py`?
