### ISSUE TITLE
Similar "fails to build wheel" issue to #26 and #27

### ISSUE THREAD

**Issue by He-zl** [idies/pyJHTDB#28]
I am using a Windows 10 device and anaconda to install.

I used "pip install pyJHTBD" and it failed saying

> Failed to build pyJHTDB
Installing collected packages: pyJHTDB
    Running setup.py install for pyJHTDB ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\67307\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\67307\\AppData\\Local\\Temp\\pip-install-zue45wtf\\pyJHTDB\\setup.py'"'"'; __file__='"'"'C:\\Users\\67307\\AppData\\Local\\Temp\\pip-install-zue45wtf\\pyJHTDB\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\67307\AppData\Local\Temp\pip-record-j9vpb34w\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\67307\anaconda3\Include\pyJHTDB'
         cwd: C:\Users\67307\AppData\Local\Temp\pip-install-zue45wtf\pyJHTDB\
    Complete output (74 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\dbinfo.py -> build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\generic_splines.py -> build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\interpolator.py -> build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\libJHTDB.py -> build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\misc.py -> build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\MortonIndex.py -> build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\test.py -> build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\test_data.py -> build\lib.win-amd64-3.7\pyJHTDB
    copying pyJHTDB\__init__.py -> build\lib.win-amd64-3.7\pyJHTDB
    creating build\lib.win-amd64-3.7\pyJHTDB\data
    copying pyJHTDB\data\channel_xgrid.npy -> build\lib.win-amd64-3.7\pyJHTDB\data
    copying pyJHTDB\data\channel_ygrid.npy -> build\lib.win-amd64-3.7\pyJHTDB\data
    copying pyJHTDB\data\channel_zgrid.npy -> build\lib.win-amd64-3.7\pyJHTDB\data
    copying pyJHTDB\data\channel5200_ygrid.npy -> build\lib.win-amd64-3.7\pyJHTDB\data
    copying pyJHTDB\data\transition_bl_ygrid.npy -> build\lib.win-amd64-3.7\pyJHTDB\data
    running build_ext
    building 'libJHTDB' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\C
    creating build\temp.win-amd64-3.7\Release\turblib
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iturblib -Ic:\users\67307\anaconda3\include -Ic:\users\67307\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /TcC/local_tools.c /Fobuild\temp.win-amd64-3.7\Release\C/local_tools.obj
    local_tools.c
    C/local_tools.c(35): warning C4305: 'initializing': truncation from 'double' to 'float'
    C/local_tools.c(66): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(78): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(82): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(83): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(84): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(140): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(151): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(155): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(156): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(157): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(203): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(214): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(218): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(219): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(220): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(223): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(184): warning C4101: 'valtmp': unreferenced local variable
    C/local_tools.c(184): warning C4101: 'ztmp': unreferenced local variable
    C/local_tools.c(184): warning C4101: 'xtmp': unreferenced local variable
    C/local_tools.c(184): warning C4101: 'ytmp': unreferenced local variable
    C/local_tools.c(184): warning C4101: 'rad0': unreferenced local variable
    C/local_tools.c(184): warning C4101: 'stmp': unreferenced local variable
    C/local_tools.c(306): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(313): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    C/local_tools.c(289): warning C4101: 'valtmp': unreferenced local variable
    C/local_tools.c(289): warning C4101: 'ztmp': unreferenced local variable
    C/local_tools.c(289): warning C4101: 'xtmp': unreferenced local variable
    C/local_tools.c(289): warning C4101: 'ytmp': unreferenced local variable
    C/local_tools.c(289): warning C4101: 'stmp': unreferenced local variable
    C/local_tools.c(289): warning C4101: 'bsize': unreferenced local variable
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iturblib -Ic:\users\67307\anaconda3\include -Ic:\users\67307\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcturblib/turblib.c /Fobuild\temp.win-amd64-3.7\Release\turblib/turblib.obj
    turblib.c
    turblib/turblib.c(86): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    turblib/turblib.c(411): warning C4013: 'bzero' undefined; assuming extern returning int
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iturblib -Ic:\users\67307\anaconda3\include -Ic:\users\67307\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcturblib/soapC.c /Fobuild\temp.win-amd64-3.7\Release\turblib/soapC.obj
    soapC.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iturblib -Ic:\users\67307\anaconda3\include -Ic:\users\67307\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcturblib/soapClient.c /Fobuild\temp.win-amd64-3.7\Release\turblib/soapClient.obj
    soapClient.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iturblib -Ic:\users\67307\anaconda3\include -Ic:\users\67307\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcturblib/stdsoap2.c /Fobuild\temp.win-amd64-3.7\Release\turblib/stdsoap2.obj
    stdsoap2.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\67307\anaconda3\libs /LIBPATH:c:\users\67307\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit_libJHTDB build\temp.win-amd64-3.7\Release\C/local_tools.obj build\temp.win-amd64-3.7\Release\turblib/turblib.obj build\temp.win-amd64-3.7\Release\turblib/soapC.obj build\temp.win-amd64-3.7\Release\turblib/soapClient.obj build\temp.win-amd64-3.7\Release\turblib/stdsoap2.obj /OUT:build\lib.win-amd64-3.7\libJHTDB.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\C\libJHTDB.cp37-win_amd64.lib
    LINK : error LNK2001: unresolved external symbol PyInit_libJHTDB
    build\temp.win-amd64-3.7\Release\C\libJHTDB.cp37-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\67307\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\67307\\AppData\\Local\\Temp\\pip-install-zue45wtf\\pyJHTDB\\setup.py'"'"'; __file__='"'"'C:\\Users\\67307\\AppData\\Local\\Temp\\pip-install-zue45wtf\\pyJHTDB\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\67307\AppData\Local\Temp\pip-record-j9vpb34w\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\67307\anaconda3\Include\pyJHTDB' Check the logs for full command output.

You mentioned that this is a complex issue about the code. Just wondering whether you have find out where the problem is?

In #27, you mentioned about using zeep. In terms of using the code, Is that installing using Zeep the same compared with installing using Pip?

**Comment by zzwz02** [comment]
Please read "README.md":
We notice the compilation error in Windows, and provide a temperary workaround in examples\Use_JHTDB_in_windows.ipynb. This method use zeep package. Should be as convient as pyJHTDB.
