### ISSUE TITLE
example ipython notebooks

### ISSUE THREAD

**Issue by chichilalescu** [idies/pyJHTDB#3]
I found out that ipython notebooks exist.
we should definitely have an example of pyJHTDB usage in that form...

**Comment by alexlib** [comment]
Thanks for the great package - we need to use GetPosition - do you have an example for it in Python? Notebook? Thanks in advance

**Comment by chichilalescu** [comment]
I can't go through the package now, but I'll see what examples we have and let you know. as far as I can remember, I did put in the functionality.

**Comment by chichilalescu** [comment]
I've added an example with commit caf32a60e46138a550c5923a973897f1f29de759.
Basically there's a method of the libJHTDB objects that returns trajectories, at a desired density of samples in time. Please let us know if you'd like more explanations with the code.

**Comment by chichilalescu** [comment]
One more comment: the relevant method is defined in `pyJHTDB/libJHTDB.py` at line 253. It's an almost direct call of the C function itself, with some minor tweaking for the sampling. The important bit is that if a finely spaced trajectory is desired, this will be more expensive.

**Comment by alexlib** [comment]
Thanks a lot.
