### ISSUE TITLE
exposed auth_token

### ISSUE THREAD

**Issue by alexlib** [idies/pyJHTDB#31]
in SDEs.ipynb somebody exposed a token

**Comment by chichilalescu** [comment]
Thank you.

I guess you're referring to the "zhao.wu" token?

@zzwz02, it looks like this was your commit last february. I'd recommend
to replace with the "testing" token that I used, update the repository,
and request that the old "zhao.wu" token is removed, with a new one
generated to replace it.

Best,
Cristian L

On Sat, 02 Jan 2021 09:41:40 -0800
Alex Liberzon <notifications@github.com> wrote:

> in SDEs.ipynb somebody exposed a token 
> 


-- 
Dr. Cristian C Lalescu

Guest with MPRG Wilczek,
Max Planck Institute for Dynamics and Self Organization

Contact:
Application Support Group
Max Planck Computing and Data Facility
Gießenbachstraße 2
85748 Garching
Germany

**Comment by mzwang2012** [comment]
I have replaced the exposed token with the testing token. Thanks again for spotting this issue!
