### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by petebachant** [idies/pyJHTDB#9]
Attempting to run `python setup.py install` gives

```bash
$ python setup.py install
running install
/home/pete/anaconda3/lib/python3.4/site-packages/setuptools-14.3-py3.4.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'llvmlite (0.2.2-1-gbcb15be)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
running bdist_egg
running egg_info
writing pyJHTDB.egg-info/PKG-INFO
writing requirements to pyJHTDB.egg-info/requires.txt
writing top-level names to pyJHTDB.egg-info/top_level.txt
writing dependency_links to pyJHTDB.egg-info/dependency_links.txt
reading manifest file 'pyJHTDB.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'turblib/turblib.c'
warning: no files found matching 'turblib/soapC.c'
warning: no files found matching 'turblib/soapClient.c'
warning: no files found matching 'turblib/stdsoap2.c'
warning: no files found matching 'turblib/*.h'
warning: no files found matching 'turblib/*.nsmap'
writing manifest file 'pyJHTDB.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'libJHTDB' extension
creating build/temp.linux-x86_64-3.4
creating build/temp.linux-x86_64-3.4/C
creating build/temp.linux-x86_64-3.4/turblib
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DCUTOUT_SUPPORT=1 -Iturblib -I/home/pete/anaconda3/include/python3.4m -c C/local_tools.c -o build/temp.linux-x86_64-3.4/C/local_tools.o
C/local_tools.c:38:21: fatal error: turblib.h: No such file or directory
 #include <turblib.h>
                     ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

I am on Linux Mint using Python 3.4 installed with Anaconda. Installing via pip works fine.

**Comment by chichilalescu** [comment]
Hi Pete,

Please try the following:

python update_turblib.py
python setup.py install

If it works, I'll just need to update the README.rst...

Best,
Chichi L

On 03/18/2015 12:44 PM, Pete Bachant wrote:
> Attempting to run |python setup.py install| gives
>
> $ python setup.py install
> running install
> /home/pete/anaconda3/lib/python3.4/site-packages/setuptools-14.3-py3.4.egg/pkg_resources/__init__.py:2512: PEP440Warning:'llvmlite (0.2.2-1-gbcb15be)'  is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
> running bdist_egg
> running egg_info
> writing pyJHTDB.egg-info/PKG-INFO
> writing requirements to pyJHTDB.egg-info/requires.txt
> writing top-level names to pyJHTDB.egg-info/top_level.txt
> writing dependency_links to pyJHTDB.egg-info/dependency_links.txt
> reading manifest file'pyJHTDB.egg-info/SOURCES.txt'
> reading manifest template'MANIFEST.in'
> warning: no files found matching'turblib/turblib.c'
> warning: no files found matching'turblib/soapC.c'
> warning: no files found matching'turblib/soapClient.c'
> warning: no files found matching'turblib/stdsoap2.c'
> warning: no files found matching'turblib/*.h'
> warning: no files found matching'turblib/*.nsmap'
> writing manifest file'pyJHTDB.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> building'libJHTDB'  extension
> creating build/temp.linux-x86_64-3.4
> creating build/temp.linux-x86_64-3.4/C
> creating build/temp.linux-x86_64-3.4/turblib
> gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DCUTOUT_SUPPORT=1 -Iturblib -I/home/pete/anaconda3/include/python3.4m -c C/local_tools.c -o build/temp.linux-x86_64-3.4/C/local_tools.o
> C/local_tools.c:38:21: fatal error: turblib.h: No such file or directory
>   #include <turblib.h>
>                       ^
> compilation terminated.
> error:command  'gcc'  failed withexit  status 1
>
> I am on Linux Mint using Python 3.4 installed with Anaconda. Installing
> via pip works fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idies/pyJHTDB/issues/9>.
>

-- 
Cristian Constantin Lalescu
Postdoctoral Researcher
Department of Applied Mathematics & Statistics
3400 North Charles Street
The Johns Hopkins University
Baltimore, Maryland 21218-2682 USA

**Comment by petebachant** [comment]
That seems to have worked!
